/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tweetanalyzer.gui;

import tweetanalyzer.analyze.NLP;

/**
 *
 * @author HENSEL
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadLabel = new javax.swing.JLabel();
        loadLabel.setVisible(false);
        jProgressBar = new javax.swing.JProgressBar();
        jProgressBar.setVisible(false);
        enButton = new javax.swing.JButton();
        deButton = new javax.swing.JButton();
        chooseLabel = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 18, 50));
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        loadLabel.setForeground(new java.awt.Color(255, 255, 255));
        loadLabel.setText("Lade Bibliotheken...");
        jPanel1.add(loadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jProgressBar.setIndeterminate(true);
        jProgressBar.setPreferredSize(new java.awt.Dimension(146, 10));
        jProgressBar.setRequestFocusEnabled(false);
        jPanel1.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 291, 400, 9));

        enButton.setBackground(new java.awt.Color(13, 37, 86));
        enButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        enButton.setForeground(new java.awt.Color(255, 255, 255));
        enButton.setText("Englisch");
        enButton.setContentAreaFilled(false);
        enButton.setMargin(new java.awt.Insets(2, 10, 2, 10));
        enButton.setOpaque(true);
        enButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enButtonActionPerformed(evt);
            }
        });
        jPanel1.add(enButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 90, 25));

        deButton.setBackground(new java.awt.Color(13, 37, 86));
        deButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        deButton.setForeground(new java.awt.Color(255, 255, 255));
        deButton.setText("Deutsch");
        deButton.setContentAreaFilled(false);
        deButton.setMargin(new java.awt.Insets(2, 10, 2, 10));
        deButton.setOpaque(true);
        deButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, 25));

        chooseLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        chooseLabel.setForeground(new java.awt.Color(255, 255, 255));
        chooseLabel.setText("Sprache der Bibliotheken:");
        jPanel1.add(chooseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        titleLabel1.setBackground(new java.awt.Color(204, 204, 204));
        titleLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(204, 204, 204));
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel1.setText("#Twitter-Datenanalyse");
        jPanel1.add(titleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 50));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enButtonActionPerformed
        loadLibraries("en");
    }//GEN-LAST:event_enButtonActionPerformed

    private void deButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deButtonActionPerformed
        loadLibraries("de");
    }//GEN-LAST:event_deButtonActionPerformed

//    public boolean isConnectedToServer(String url, int timeout) {
//
//        try {
//            URL serverURL = new URL(url);
//            URLConnection urlconn = serverURL.openConnection();
//            urlconn.setConnectTimeout(timeout);
//            urlconn.connect();
//            return true;
//        } catch (IOException e) {
//
//        } catch (IllegalStateException e) {
//        }
//        return false;
//
//    }
    public void loadLibraries(String lang) {
        Runnable runner = new Runnable() {
            public void run() {
                deButton.setVisible(false);
                enButton.setVisible(false);
                chooseLabel.setVisible(false);
                jProgressBar.setVisible(true);
                loadLabel.setVisible(true);
                NLP.init(lang);
                dispose();
                new GUI(lang).setVisible(true);
            }
        };
        Thread t = new Thread(runner, "Library Loader");
        t.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseLabel;
    private javax.swing.JButton deButton;
    private javax.swing.JButton enButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JLabel loadLabel;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables
}
